# Generated by Django 2.2.6 on 2020-07-30 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-date_create']},
        ),
        migrations.RemoveField(
            model_name='post',
            name='date_modify',
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(db_index=True, max_length=256),
        ),
    ]
